### ISSUE TITLE
Empty continuation line found in:

### ISSUE THREAD

**Issue by reddytocode** [loitho/docker-opencv-cuda#1]
RUN apt-get update &&         apt-get install -y 	python-pip         build-essential         cmake         git         wget         unzip         yasm         pkg-config         libswscale-dev         libtbb2         libtbb-dev         libjpeg-dev         libpng-dev         libtiff-dev         libjasper-dev         libavformat-dev         libpq-dev 	libxine2-dev 	libglew-dev 	libtiff5-dev 	zlib1g-dev 	libjpeg-dev 	libpng12-dev 	libjasper-dev 	libavcodec-dev 	libavformat-dev 	libavutil-dev 	libpostproc-dev 	libswscale-dev 	libeigen3-dev 	libtbb-dev 	libgtk2.0-dev 	pkg-config         python-dev         python-numpy         python3-dev         python3-numpy     && rm -rf /var/lib/apt/lists/*
[WARNING]: Empty continuation lines will become errors in a future release.

**Comment by loitho** [comment]
Hi,
That's just a warning because I put empty continuation lines to make for a clearer reading of the file.
https://github.com/laradock/laradock/issues/1164
I could replace them with "echo "something something" if this becomes an issue
